name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm build
      run: |
        npm install
        npm run build

  deploy:
    name: Publish to GitHub pages
    needs: build
    runs-on: ubuntu-latest    
    steps:
    - name: Publish
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
