name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

  build:
    name: Build and push to gh-pages
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm build
      run: |
        npm install
        npm run build
    - name: Publish
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
